In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_csv('../sales_data.csv')

In [4]:
df.head()

,Order ID,Product,Quantity,Price Each,Date,Purchase Address,Month,Revenue,Year,Month_Name,Year_Month
0,150502,iPhone,1.0,700.00,2019-02-18 01:35:00,"866 Spruce St, Portland, ME 04101",2,700.00,2019,February,2019-02
1,150503,AA Batteries (4-pack),1.0,3.84,2019-02-13 07:24:00,"18 13th St, San Francisco, CA 94016",2,3.84,2019,February,2019-02
2,150504,27in 4K Gaming Monitor,1.0,389.99,2019-02-18 09:46:00,"52 6th St, New York City, NY 10001",2,389.99,2019,February,2019-02
3,150505,Lightning Charging Cable,1.0,14.95,2019-02-02 16:47:00,"129 Cherry St, Atlanta, GA 30301",2,14.95,2019,February,2019-02
4,150506,AA Batteries (4-pack),2.0,3.84,2019-02-28 20:32:00,"548 Lincoln St, Seattle, WA 98101",2,7.68,2019,February,2019-02

In [6]:
df1 = df.copy()

In [ ]:
df1 = df1["Year_Month"] != "2020-01"

In [10]:
df1.head()

0    True
1    True
2    True
3    True
4    True
Name: Year_Month, dtype: bool

In [11]:
df2 = df.copy()

In [12]:
df2.head()

,Order ID,Product,Quantity,Price Each,Date,Purchase Address,Month,Revenue,Year,Month_Name,Year_Month
0,150502,iPhone,1.0,700.00,2019-02-18 01:35:00,"866 Spruce St, Portland, ME 04101",2,700.00,2019,February,2019-02
1,150503,AA Batteries (4-pack),1.0,3.84,2019-02-13 07:24:00,"18 13th St, San Francisco, CA 94016",2,3.84,2019,February,2019-02
2,150504,27in 4K Gaming Monitor,1.0,389.99,2019-02-18 09:46:00,"52 6th St, New York City, NY 10001",2,389.99,2019,February,2019-02
3,150505,Lightning Charging Cable,1.0,14.95,2019-02-02 16:47:00,"129 Cherry St, Atlanta, GA 30301",2,14.95,2019,February,2019-02
4,150506,AA Batteries (4-pack),2.0,3.84,2019-02-28 20:32:00,"548 Lincoln St, Seattle, WA 98101",2,7.68,2019,February,2019-02

In [13]:
df2 = df2[~((df2["Year"] == 2020) & (df2["Month"] == 1))]

In [14]:
df2[df2["Year_Month"] == "2020-01"]

Empty DataFrame
Columns: [Order ID, Product, Quantity, Price Each, Date, Purchase Address, Month, Revenue, Year, Month_Name, Year_Month]
Index: []

In [15]:
df = df2

In [16]:
df[df["Year_Month"] == "2020-01"]

Empty DataFrame
Columns: [Order ID, Product, Quantity, Price Each, Date, Purchase Address, Month, Revenue, Year, Month_Name, Year_Month]
Index: []

In [17]:
df.head()

,Order ID,Product,Quantity,Price Each,Date,Purchase Address,Month,Revenue,Year,Month_Name,Year_Month
0,150502,iPhone,1.0,700.00,2019-02-18 01:35:00,"866 Spruce St, Portland, ME 04101",2,700.00,2019,February,2019-02
1,150503,AA Batteries (4-pack),1.0,3.84,2019-02-13 07:24:00,"18 13th St, San Francisco, CA 94016",2,3.84,2019,February,2019-02
2,150504,27in 4K Gaming Monitor,1.0,389.99,2019-02-18 09:46:00,"52 6th St, New York City, NY 10001",2,389.99,2019,February,2019-02
3,150505,Lightning Charging Cable,1.0,14.95,2019-02-02 16:47:00,"129 Cherry St, Atlanta, GA 30301",2,14.95,2019,February,2019-02
4,150506,AA Batteries (4-pack),2.0,3.84,2019-02-28 20:32:00,"548 Lincoln St, Seattle, WA 98101",2,7.68,2019,February,2019-02

In [19]:
df.to_csv('../sales_data.csv', index=False)